version: "3"
services:

  mumble:
    image: docker.pkg.github.com/flipdot/mumble-docker/mumble:latest
    # build: mumble/.
    command: /usr/bin/murmurd -v -fg -ini /data/config.ini
    volumes:
      - ./data:/data
    ports:
      - 64738:64738
      - 64738:64738/udp
    environment:
      TZ: Europe/Berlin
    restart: unless-stopped

  botamusique:
    image: docker.pkg.github.com/flipdot/mumble-docker/botamusique:latest
    #build: plugins/botamusique-docker/.
    volumes:
      - ./data/botamusique:/data/
    depends_on:
      - mumble
    restart: unless-stopped
