version: "3"
services:
  mumble:
    build: mumble/.
    volumes:
      - ./data:/etc/mumble
    ports:
      - 64738:64738
      - 64738:64738/udp
    environment:
      TZ: Europe/Berlin
    restart: unless-stopped
  botamusique:
    build: plugins/botamusique-docker/.
