version: "3"
services:

  mumble:
    image: docker.pkg.github.com/flipdot/docker-mumble/mumble:latest
    command: /usr/bin/murmurd -v -fg -ini /etc/murmur/murmur.ini
    volumes:
      - ./data:/etc/murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    environment:
      TZ: Europe/Berlin
    restart: unless-stopped

  botamusique:
    image: docker.pkg.github.com/flipdot/docker-mumble/botamusique:latest
    volumes:
      - ./data/botamusique:/data/
