name: Docker-Compose CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # celt submodule has dumb http transport
        submodules: recursive

    - name: Build the Docker image
      run: docker-compose build

    - name: Generate a fake certificate
      run: |
        openssl req -x509 \
          -newkey rsa:4096 \
          -nodes \
          -keyout data/privkey.pem \
          -out data/fullchain.pem \
          -days 30 \
          -subj '/CN=localhost'

    - name: Run
      run: docker-compose up &
    - name: Test
      run: |
        echo "=== Waiting for server to start... ==="
        success=false
        for i in {1..10}; do
          echo "=== Trying now ==="
          if python3 ping.py localhost 64738; then
            echo "=== Success! ==="
            success=true
            break
          fi
          sleep 1
        done
        if [ "$success" != true ]; then
          echo "=== Fail! ==="
        fi

    - name: Teardown
      run: docker-compose down -v

    - name: Check mumble database exists
      run: '[ -s data/murmur.sqlite ]'
    - name: Check botamusique database exists
      run: '[ -s data/botamusique.db ]'
